backup_path: '/home/xin053/swConfigBackup'
keep_time: 30
hosts:
    - name: xxxH3C6800
      type: h3c
      ip: xxx.xxx.xxx.xxx
      port: 22
      username: xxx
      password: xxx
    - name: xxxCE6810-01
      type: huawei
      ip: xxx.xxx.xxx.xxx
      port: 22
      username: xxx
      password: xxx